### ISSUE TITLE
upgrade to angular 5?

### ISSUE THREAD

**Issue by dilotec-2015** [sureshchahal/angular2-adal#75]
could you upgrade the dependecies and HttpClient to angular 5?

it seems to work with angular 5, but after compilation i get following warning:

WARNING in ./node_modules/ng2-adal/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\xampp\htdocs\fox-backend-ng5\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\xampp\htdocs\fox-backend-ng5\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\xampp\htdocs\fox-backend-ng5\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\xampp\htdocs\fox-backend-ng5\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\xampp\htdocs\fox-backend-ng5\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\xampp\htdocs\fox-backend-ng5\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\xampp\htdocs\fox-backend-ng5\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ng2-adal/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ng2-adal/dist/services/authHttp.service.js
 @ ./node_modules/ng2-adal/dist/modules/authHttp.module.js
 @ ./node_modules/ng2-adal/dist/modules.js
 @ ./node_modules/ng2-adal/dist/core.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?https://0.0.0.0:0 ./src/main.ts

**Comment by ToKaDev** [comment]
+1

**Comment by skorunka** [comment]
Do you guys plan to update this library to be compatible with ng5 (no warnings)? Thank you.

**Comment by skorunka** [comment]
What helped to me so far, is just to update the `angular2-adal` dependencies to the latest and `npm i`.

**Comment by godzillar** [comment]
I've got the same issue.

**Comment by teban1812** [comment]
+1

**Comment by rjwijnen** [comment]
+1

**Comment by rjwijnen** [comment]
I tried to edit this library to support. Please check if helps you out: #77

**Comment by wrss2** [comment]
+1 i compile and its working on 5.0.5 angular
it not create Authorization header and  not conect with adal not creating iframe ;/

**Comment by test0017** [comment]
I am using ng2-adal and its showing WARNING in ./node_modules/ng2-adal/node_modules/@angular/core/@angular/core.es5.js  warning when i upgraded the application in to Angular5
I have tried adal-angular5  and do-adal-angular5 , Its working but calling ng-init 2 times .
Please let me know about it .
Thanks .
