### ISSUE TITLE
Webpack warning when using Angular 5

### ISSUE THREAD

**Issue by ottokruse** [sureshchahal/angular2-adal#79]
Up and running like a charm in Angular 5 without any alterations compared to our Angular 4 app, so that's great.

So it works, but .... webpack throws this warning message upon compilation.

Not sure if this issue belongs here or at Angular-CLI project (excuse me) but ng2-adal is mentioned in the stack trace.

WARNING in ./node_modules/ng2-adal/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\git\personen-app-ng5\node_modules\webpack\lib\dependencies\ContextDep
endency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\git\personen-app-ng5\node_modules\webpack\lib\Compilation.js:70
3:24)
    at Compilation.finish (C:\git\personen-app-ng5\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\git\personen-app-ng5\node_modules\webpack\lib\Compiler.js:502:17)
    at C:\git\personen-app-ng5\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\git\personen-app-ng5\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\git\personen-app-ng5\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ng2-adal/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ng2-adal/dist/services/adal.service.js
 @ ./node_modules/ng2-adal/dist/services.js
 @ ./node_modules/ng2-adal/dist/core.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by rjwijnen** [comment]
See https://github.com/sureshchahal/angular2-adal/pull/77/files

**Comment by savageqm** [comment]
Any timeline for possible release of this fix?

**Comment by jmtrz** [comment]
Is this fixed alraedy? if yes how do we implement the fix?

**Comment by test0017** [comment]
I am using ng2-adal and its showing WARNING in ./node_modules/ng2-adal/node_modules/@angular/core/@angular/core.es5.js warning when i upgraded the application in to Angular5
I have tried adal-angular5 and do-adal-angular5 , Its working but calling ng-init 2 times .
Please let me know about it .
Thanks .
